using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


//was not autogenerated since it had on cascade on delete

namespace SupportDeskEF.Models
{
    public class TicketTag
    {
        public int TicketId { get; set; }
        public virtual Ticket Ticket { get; set; } = null!;
        public int TagId { get; set; }
        public virtual Tag Tag { get; set; } = null!;
        
    }
}
